#
# Global setting
###########################################
mybatis:
  type-aliases-package: kr.co.ensmart.frameworkdemo.**.dto
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

debug: true
  
app:
  name: test
  env: default

---
#
# LOCAL Setting
###########################################
server:
  port: 8080

spring:
  profiles: local

  datasource:
    #url: jdbc:postgresql://localhost:5432/postgres?currentSchema=x2commerce
    url: jdbc:log4jdbc:postgresql://localhost:5432/postgres?currentSchema=x2commerce
    #driver-class-name: org.postgresql.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: x2commerce
    password: x2commerce123!
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      connection-timeout: 30000
      validation-timeout: 5000
      max-lifetime: 1800000
      idle-timeout: 300000

app:
  env: local

---
#
# DEV Setting
###########################################
server:
  port: 8080

spring:
  profiles: dev

  datasource:
    #url: jdbc:postgresql://localhost:5432/postgres?currentSchema=x2commerce
    url: jdbc:log4jdbc:postgresql://localhost:5432/postgres?currentSchema=x2commerce
    #driver-class-name: org.postgresql.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: x2commerce
    password: x2commerce123!
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      connection-timeout: 30000
      validation-timeout: 5000
      max-lifetime: 1800000
      idle-timeout: 300000

app:
  env: local
